#!/usr/bin/env bash
# generates docs/KEYBINDS.md from the niri keybinds and the shell's ipc targets.
set -euo pipefail

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
binds=$root/home/.config/niri/keybinds.kdl
shell=$root/home/.config/ringo-shell/shell.qml
doc=$root/docs/KEYBINDS.md

usage() {
    cat <<'EOF'
usage: gen-keybinds-doc.sh [--check]

Regenerates docs/KEYBINDS.md from home/.config/niri/keybinds.kdl and the
IpcHandler targets in home/.config/ringo-shell/shell.qml.

  --check    do not write; exit non-zero and print a diff when the file is stale
EOF
}

check=0
case ${1:-} in
    '') ;;
    --check) check=1 ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'gen-keybinds-doc: unknown argument: %s\n' "$1" >&2; exit 2 ;;
esac
if [ "$#" -gt 1 ]; then
    printf 'gen-keybinds-doc: too many arguments\n' >&2
    usage >&2
    exit 2
fi
for f in "$binds" "$shell"; do
    if [ ! -f "$f" ]; then
        printf 'gen-keybinds-doc: missing source: %s\n' "$f" >&2
        exit 1
    fi
done

generate() {
    cat <<'EOF'
# Keybinds

<!-- generated by scripts/gen-keybinds-doc.sh; do not edit by hand -->

Every binding below comes from `~/.config/niri/keybinds.kdl`; the shell section is
generated from the `IpcHandler` targets in `home/.config/ringo-shell/shell.qml`.
Regenerate with `scripts/gen-keybinds-doc.sh` after changing either file
(`scripts/gen-keybinds-doc.sh --check` fails while this document is stale).

`Mod` is Super / the Windows key.
EOF

    awk '
    function trim(s) { gsub(/^[[:space:]]+/, "", s); gsub(/[[:space:]]+$/, "", s); return s }

    # drops a // comment that is not inside a double quoted string
    function strip_comment(s,    i, c, q, out) {
        out = ""; q = 0
        for (i = 1; i <= length(s); i++) {
            c = substr(s, i, 1)
            if (q && c == "\\") { out = out c substr(s, i + 1, 1); i++; continue }
            if (c == "\"") q = !q
            if (c == "/" && !q && substr(s, i + 1, 1) == "/") return out
            out = out c
        }
        return out
    }

    # counts braces outside strings; leaves them in opens/closes
    function count_braces(s,    i, c, q) {
        opens = 0; closes = 0; q = 0
        for (i = 1; i <= length(s); i++) {
            c = substr(s, i, 1)
            if (q && c == "\\") { i++; continue }
            if (c == "\"") q = !q
            else if (!q && c == "{") opens++
            else if (!q && c == "}") closes++
        }
    }

    # escape pipes and drop backticks so any action survives a markdown table cell
    function cell(s,    i, c, out) {
        out = ""
        for (i = 1; i <= length(s); i++) {
            c = substr(s, i, 1)
            if (c == "|") out = out "\\|"
            else if (c == "`") out = out "\x27"
            else out = out c
        }
        return out
    }

    function heading(title) {
        printf "\n## %s\n\n| Keys | Action |\n| :--- | :--- |\n", title
        printed = title
    }

    # one binding line: keys [props] { action }
    function emit(text,    i1, i2, k, prefix, keys, title, action, row, celltext) {
        i1 = 0; q = 0
        for (i = 1; i <= length(text); i++) {
            c = substr(text, i, 1)
            if (q && c == "\\") { i++; continue }
            if (c == "\"") { q = !q; continue }
            if (!q && c == "{") { i1 = i; break }
        }
        if (i1 == 0) return
        i2 = 0
        for (i = length(text); i >= 1; i--) if (substr(text, i, 1) == "}") { i2 = i; break }
        if (i2 <= i1) return

        prefix = trim(substr(text, 1, i1 - 1))
        if (prefix == "") return
        keys = prefix
        sub(/[[:space:]].*/, "", keys)

        title = ""
        if (match(prefix, /hotkey-overlay-title="[^"]*"/)) {
            title = substr(prefix, RSTART + 22, RLENGTH - 23)
        }

        action = trim(substr(text, i1 + 1, i2 - i1 - 1))
        gsub(/[[:space:]]+/, " ", action)
        sub(/;+$/, "", action)
        if (action == "") return

        if (explicit) {
            if (printed != section) heading(section)
        } else if (newblock || printed == "") {
            # no section comment above this block: label it after its first binding
            heading(title != "" ? title : action)
        }
        newblock = 0

        row = "`" cell(keys) "`"
        celltext = (title == "" ? "`" cell(action) "`" : cell(title) " — `" cell(action) "`")
        printf "| %s | %s |\n", row, celltext
    }

    BEGIN { inbinds = 0; pending = ""; section = ""; printed = ""; explicit = 0; newblock = 1 }

    {
        t = trim($0)
        if (!inbinds) {
            if (t ~ /^binds[[:space:]]*\{/) inbinds = 1
            next
        }
        if (pending == "") {
            if (t == "") { newblock = 1; next }
            if (substr(t, 1, 2) == "//") {
                section = trim(substr(t, 3))
                explicit = (section != "") ? 1 : 0
                newblock = (section == "") ? 1 : 0
                next
            }
            if (substr(t, 1, 2) == "/*") next
            if (t == "}") { inbinds = 0; next }
        }
        line = strip_comment($0)
        pending = (pending == "" ? line : pending " " line)
        count_braces(line)
        nobraces += opens
        nbraces += closes
        # a binding is complete once its braces balance; multi-line bindings
        # (an overlay title or the action on the next line) accumulate first
        if (nobraces > 0 && nobraces == nbraces) {
            emit(pending)
            pending = ""; nobraces = 0; nbraces = 0
        }
    }
    ' "$binds"

    awk '
    function trim(s) { gsub(/^[[:space:]]+/, "", s); gsub(/[[:space:]]+$/, "", s); return s }

    # net brace depth of a line, ignoring braces inside strings
    function brace_delta(s,    i, c, q, d) {
        d = 0; q = 0
        for (i = 1; i <= length(s); i++) {
            c = substr(s, i, 1)
            if (q && c == "\\") { i++; continue }
            if (c == "\"") q = !q
            else if (!q && c == "{") d++
            else if (!q && c == "}") d--
        }
        return d
    }

    # escape pipes and drop backticks so any action survives a markdown table cell
    function cell(s,    i, c, out) {
        out = ""
        for (i = 1; i <= length(s); i++) {
            c = substr(s, i, 1)
            if (c == "|") out = out "\\|"
            else if (c == "`") out = out "\x27"
            else out = out c
        }
        return out
    }

    function emit(    n, parts, i, names) {
        if (target == "" || funcs == "") return
        if (!printed) {
            print ""
            print "## Shell Commands (IPC)"
            print ""
            print "Commands the shell exposes over IPC, called as `ringo-shell call <target> <function>`."
            print ""
            print "| Target | Functions |"
            print "| :--- | :--- |"
            printed = 1
        }
        n = split(funcs, parts, " ")
        names = ""
        for (i = 1; i <= n; i++)
            if (parts[i] != "") names = names (names == "" ? "" : " ") "`" cell(parts[i]) "`"
        printf "| `%s` | %s |\n", cell(target), names
    }

    BEGIN { inside = 0; depth = 0; target = ""; funcs = ""; printed = 0 }

    /^[[:space:]]*IpcHandler[[:space:]]*\{/ { inside = 1; depth = 1; target = ""; funcs = ""; next }

    inside {
        if (depth == 1) {
            t = trim($0)
            if (substr(t, 1, 7) == "target:") {
                target = trim(substr(t, 8))
                gsub(/"/, "", target)
            } else if (substr(t, 1, 8) == "function") {
                name = trim(substr(t, 9))
                sub(/\(.*$/, "", name)
                name = trim(name)
                if (name != "") funcs = funcs (funcs == "" ? "" : " ") name
            }
        }
        depth += brace_delta($0)
        if (depth <= 0) { emit(); inside = 0; depth = 0 }
    }
    ' "$shell"
}

if [ "$check" -eq 1 ]; then
    if [ ! -f "$doc" ]; then
        printf 'gen-keybinds-doc: %s does not exist; run scripts/gen-keybinds-doc.sh\n' "$doc" >&2
        exit 1
    fi
    tmp=$(mktemp)
    trap 'rm -f "$tmp"' EXIT
    generate >"$tmp"
    if ! diff -u "$doc" "$tmp"; then
        printf 'gen-keybinds-doc: %s is out of date\n' "$doc" >&2
        exit 1
    fi
    exit 0
fi

mkdir -p "$(dirname -- "$doc")"
generate >"$doc"
printf 'gen-keybinds-doc: wrote %s\n' "$doc"
